#!/bin/sh /etc/rc.common
START=1OO

PROG=/usr/bin/oled

stop_oled() {
	kill -2 $(pgrep /usr/bin/oled)
	kill -9 $(pgrep -f /usr/sbin/netspeed)
}

stop_ttl() {
	iptables-save | grep -v "\[KTM-Tools\] --ttl-set" | iptables-restore
}

stop() {
	stop_ttl
	stop_oled
}

start_ttl() {
	if [ $(uci get ktm-tools.@ttl[0].enable) -eq 1 ]; then
		interface=$(uci get ktm-tools.@ttl[0].interface)
		ttlset=$(uci get ktm-tools.@ttl[0].ttlset)
		iptables -t mangle -I POSTROUTING -o $interface -m comment --comment "[KTM-Tools] --ttl-set" -j TTL --ttl-set $ttlset
	fi
}

start_oled(){
	if [ $(uci get ktm-tools.@oled[0].enable) -eq 0 ]; then
		exit 0
	fi

	autoswitch=$(uci get ktm-tools.@oled[0].autoswitch)
	from=$(uci get ktm-tools.@oled[0].from)
	to=$(uci get ktm-tools.@oled[0].to)

	if [ ${autoswitch} -eq 1 ]; then
		hour=$(date +"%H")                                                     
                min=$(date +"%M")                                                                      
                ihour=`expr $hour + 0`                                    
                imin=`expr $min + 0`                                                                   
                now=$(($ihour*60+$imin))                                               
                if [[ $now -lt $from || $now -gt $to ]]; then
			stop
			exit 0
		fi		
	fi
	
	# crontab daemon
	if ! grep "/etc/init.d/oled \+restart" /etc/crontabs/root >/dev/null 2>&1; then
		echo "*/15 * * * * /etc/init.d/oled restart >/dev/null 2>&1" >> /etc/crontabs/root
	fi

	speedtesttime=$(uci get ktm-tools.@oled[0].speedtesttime)
	i2cdevice=$(uci get ktm-tools.@oled[0].i2cdevice)

	nohup /usr/sbin/netspeed ${speedtesttime} >/dev/null 2>&1 &
	nohup ${PROG} "${i2cdevice}" 1 > /dev/null 2>&1 &
}

start() {
	start_ttl
	start_oled
}

 
restart_ttl(){
	stop_ttl
	start_ttl
}

restart_oled(){
	pgrep -f ${PROG} >/dev/null
	if [ $? -eq 0 ]; then
		if [ $(uci get ktm-tools.@oled[0].enable) -eq 1 ]; then
			autoswitch=$(uci get ktm-tools.@oled[0].autoswitch)
			if [ ${autoswitch} -eq 1 ]; then
				from=$(uci get ktm-tools.@oled[0].from)
				to=$(uci get ktm-tools.@oled[0].to)
				hour=$(date +"%H")                                                     
                                min=$(date +"%M")                                      
                                ihour=`expr $hour + 0`                                                 
                                imin=`expr $min + 0`                      
                                now=$(($ihour*60+$imin))                                               
                                if [[ $now -lt $from || $now -gt $to ]]; then
					stop
					exit 0
				fi		
			fi

			speedtesttime=$(uci get ktm-tools.@oled[0].speedtesttime)
			i2cdevice=$(uci get ktm-tools.@oled[0].i2cdevice)

			kill -9 $(pgrep /usr/bin/oled)
			kill -9 $(pgrep -f /usr/sbin/netspeed)

			nohup /usr/sbin/netspeed ${speedtesttime} >/dev/null 2>&1 &
			nohup ${PROG} "${i2cdevice}" 0 > /dev/null 2>&1 &
		else
			stop_oled
		fi

	else
		if [ $(uci get ktm-tools.@oled[0].enable) -eq 1 ]; then
			start_oled
		else
			exit 0
		fi
	fi	
}

restart(){
	restart_ttl
	restart_oled
}

boot(){
	start
}